### ISSUE TITLE
Used PHP version is insecure

### ISSUE THREAD

**Issue by mrbadaw** [shannah/phpjar#1]
Hello Friend,
Thanks a lot for the jar file, its useful, but please advise, how can we upgrade the php version used in thin client, since the current version 7.2.5 is in secure version and we need to upgrade it to version above 7.3.11 or above.
I am using thin jar.
please advise

**Comment by shannah** [comment]
The PHP distribution is taken from XAMPP.  I use the https://github.com/shannah/phpjar/tree/master/phpjarBuilder project to extract PHP and create the zip files, which are then placed in the bin/native directory on github.

I may be able to automate this with a github action so that it doesn't have to be done manually.  I don't have an ETA on this.

**Comment by mrbadaw** [comment]
Dear Steve,
How can we use phpjarBuilder to exract php from XAMPP manually? May you send a procedure please.
Thanks

**Comment by shannah** [comment]
I'm a little swamped right now with my day job, but all of the stuff for building the php bundles is in https://github.com/shannah/phpjar/tree/master/phpjarBuilder

Notice that there are ant targets in the build.xml file for building linux, mac, and windows.  You need to do this separately on windows, mac, and linux machines.

On Windows, you basically just install XAMPP, and then it zips up the php directory whole.  On Mac and linux, it's a little more involved.  You'll notice that it uses some custom [Ant tasks](https://github.com/shannah/phpjar/tree/master/phpjarBuilder/src/phpjarbuilder) to take the XAMPP bundles and extract out the PHP.

**Comment by mrbadaw** [comment]
Thanks a lo Steve,
we downloaded the package, used the phpjarBuilder to extract the php folder and moved it under .phpjar, and it worked.
Thanks a lot
